POST http://localhost:2020/Users/crear
content-type: application/json

{
    "nombre": "carlos",
    "email": "juan@gmail.com",
    "password": "1234"
}
#####

GET http://localhost:2020/Users/lista
content-type: application/json

####

GET http://localhost:2020/Users/busqueda/2
content-type: application/json

####
 
PUT http://localhost:2020/Users/actualizar/2
content-type: application/json

 {
    "nombre": "Juan Updated",
    "email": "juan.updated@gmail.com",
    "password": "1234"
}

#####

DELETE http://localhost:2020/Users/eliminar/1
content-type: application/json

######
POST http://localhost:2020/Users/login
content-type: application/json

{
    "email": "juan@gmail.com",
    "password": "1234"
}